from __future__ import annotations

from typing import Protocol


class CacheRepository(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...

    async def incr(self, key: str, ttl: int | None = None) -> int: ...

    async def delete(self, key: str) -> None: ...

    async def ping(self) -> bool: ...

    async def keys(self, prefix: str) -> list[str]: ...

    async def flush(self, prefix: str) -> None: ...
